apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.mysql.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
