mysql:
  namespace: mysql

  image:
    repository: mysql
    version: 8.0

  dbReplicas: 2

  resources:
    requests:
      cpu: 500m
      memory: 1Gi

  secrets:
    MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
    MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
    MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"

  VolumeClaim: 2Gi

  tolerations:
    key: "app"
    value: "mysql"
    operator: "Equal"
    effect: "NoSchedule"

  affinity:
    podaffinity:
      key: "app"
      value: "mysql"
      operator: In
      values:
      - mysql

    nodeaffinity:
      key: "app"
      value: "mysql"
      operator: In
      values:
      - mysql
