apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: {{ .Values.todoapp.namespace }}
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
