apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp
  namespace: {{ .Values.todoapp.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp
  minReplicas: {{ .Values.todoapp.HorScaling.minReplicas }}
  maxReplicas: {{ .Values.todoapp.HorScaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.todoapp.HorScaling.resourcetarget.cpu }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.todoapp.HorScaling.resourcetarget.memory }}
