apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: {{ .Values.todoapp.namespace }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.todoapp.PersistentVolume.capacity }}
  hostPath:
    path: /data/
