apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.todoapp.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.todoapp.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
